name: capstone_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  flutter_native_splash: ^2.3.10
  firebase_storage: ^11.6.9
  image_picker: ^1.0.8
  flutter_custom_clippers: ^2.1.0
  flutter_svg: ^1.1.6
  intl:
  http: ^1.2.0
  quickalert: ^1.1.0
  url_launcher: ^6.1.5
  flutter_local_notifications: ^17.1.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/education.png"
